# -*- coding: utf-8 -*-
"""Desafio01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mBTTeObsEiUS9Cd-c2lst4AGlhZBoTix
"""

#DESAFIOS INICIANTES EM PYTHON
#ALUNO: MARCOS AURELIO


#DESAFIO 1: CRIAR UMA LISTA DE INTEIROS E UM VALOR QUE DEVE SER BUSCADO.
#           O PROGRAMA DEVE RETORNAR O ÍNDICE QUE O VALOR DESEJADO SE ENCONTRA.

print("------------------------------------------------------------------------")
print("DESAFIO 1: LISTA DE INTEIROS COM BUSCA DE VALORES E RETORNOS DE ÍNDICES.")

listaInteiros = [3, 8, 10, 5, 2, 7, 1, 4, 6, 9]
valorBuscado = int(input("Digite o número que deseja pesquisar na lista: "))
print("\nNúmero buscado:", valorBuscado)

if valorBuscado in listaInteiros:
  print("\nO número >",valorBuscado,"< se encontra no índice >",listaInteiros.index(valorBuscado),"< da nossa lista.")
else:
  print("\nDesculpe, não encontramos esse número na nossa lista.")