# -*- coding: utf-8 -*-
"""AtividadeDIO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wfmhNLVfXDNnqlsA-idfZtVJGB_BzWCX
"""

#ALUNO: MARCOS AURELIO
#ATIVIDADE PRÁTICA DO CURSO "ENTENDENDO MÉTODOS EM JAVA" (DIGITAL INNOVATION ONE)

#OBJETIVO: Calcular o preço total de um empréstimo, a partir do valor solicitado.

print("Bem-vindo ao nosso sistema de empréstimos!\n")
valorDoEmprestimo = int(input("Digite o valor que você está precisando.: "))
numeroDeParcelas = int(input("Em quantas vezes deseja dividir o pagamento?: "))
taxaDeServiço = 12
jurosParcelamento = 3

taxaFinalParcelamento = 0
valorTotal = 0
valorPorMes = 0

def calcularParcelamento(taxaFinalParcelamento):
  taxaFinalParcelamento = 0
  for x in range(1, numeroDeParcelas + 1):
    taxaFinalParcelamento = jurosParcelamento * x
  print("Juros total (R$ 3 reais por parcela): R$",taxaFinalParcelamento, "reais")
  calcularValorTotal(taxaFinalParcelamento)

def calcularValorTotal(taxaFinalParcelamento):
  valorTotal = valorDoEmprestimo + taxaDeServiço + taxaFinalParcelamento
  print("\nValor total: R$",valorTotal, "reais.")
  calcularValorPorMes(valorTotal)

def calcularValorPorMes(valorTotal):
  valorPorMes = valorTotal / numeroDeParcelas
  print("Valor das parcelas: ", valorPorMes, "reais/mês.")

print("\nValor solicitado: R$",valorDoEmprestimo, "reais.")
print("Taxa de serviço: ",taxaDeServiço, "reais.")

calcularParcelamento(taxaFinalParcelamento)